version: '3'
services:
  frontend:
    restart: always
    build: ./
    command: >
      sh -c "yarn build &&
             yarn start"
    # volumes:
    #  - .:/app
    #  - /app/node_modules
    env_file:
      - ./.env
    expose:
      - '3000'
